-- AlterTable
ALTER TABLE "Barang" ALTER COLUMN "harga" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Sales" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "diskon" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "ongkir" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total_bayar" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "SalesDetail" ALTER COLUMN "harga_bandrol" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "diskon_pct" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "diskon_nilai" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "harga_diskon" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30);
